### ISSUE TITLE
pinned version {"tag":"v21.1.1"} is not available

### ISSUE THREAD

**Issue by jmcdice** [pivotal-cf/pcf-prometheus-pipeline#15]
I'm am seeing that this:

  - get: prometheus-release-blob
    version: { tag: 'v21.1.1' }

Returns this:

 - pinned version {"tag":"v21.1.1"} is not available

I think you want:
   version: { tag: 'v22.0.0' }

**Comment by mkuratczyk** [comment]
I don't want v22 because it introduces Prometheus 2 which has not been tested with this pipeline yet (or more precisely, it has been tested accidentally and doesn't work ;) ). So for the time being I want the latest v21. This pipeline worked for me yesterday, so I'd appreciate more details about your issue. Thanks

**Comment by jmcdice** [comment]
Ok, pulling the previous version of the resource (per your advice) did the trick:

fly -t concourse check-resource -r deploy-prometheus/prometheus-release-blob --from tag:v21.1.1
