### ISSUE TITLE
Could not interpolate: Expected to find exactly one matching array item for path '/instance_groups/name=prometheus' 

### ISSUE THREAD

**Issue by shyamkumarchauhan** [pivotal-cf/pcf-prometheus-pipeline#16]
Can someone please help me to identify what could be done to fix this issue ?

Could not interpolate: Expected to find exactly one matching array item for path '/instance_groups/name=prometheus' but found 0

**Comment by mkuratczyk** [comment]
Are you using the latest version of the pipeline? Seems to be related to the switch to Prometheus v2 in the bosh release v22 (https://github.com/bosh-prometheus/prometheus-boshrelease/releases/tag/v22.0.0). Currently this pipeline can't work with this version (it expects the job to be named `prometheus` but with v22+ it's `prometheus2` and therefore interpolation fails). Please make sure you are using the latest version with no modifications and report all details if it still doesn't work. Hopefully later this week I will test the pipeline with v22 and then you should be able to use it to deploy the latest prometheus-boshrelease.

**Comment by shyamkumarchauhan** [comment]
With current repo it fails when I trigger to install node-exporter .
logs below.

# fly -t pcf js -p deploy-prometheus                               name                   paused  status     next
create-uaa-clients     no      succeeded  n/a
install-node-exporter  no      failed     n/a
deploy                 no      n/a        n/a
destroy                no      n/a        n/a




Pragma: no-cache
Server: nginx/1.4.6 (Ubuntu)
Strict-Transport-Security: max-age=15552000
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Request-Id: a64626af-0208-4ad0-ba54-a4c40d0b7c53
X-Runtime: 0.025150
X-Xss-Protection: 1; mode=block
error running command: GET https://api.github.com/repos/bosh-prometheus/node-exporter-boshrelease/releases/tags/v3.0.1: 403 API rate limit exceeded for 165.225.0.87. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.); rate reset in 10m51.649310237s

...

...


.....

Server: nginx/1.4.6 (Ubuntu)
Strict-Transport-Security: max-age=15552000
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Request-Id: 66c87286-5c17-4523-953c-e75b9b8ac51a
X-Runtime: 0.521243
X-Xss-Protection: 1; mode=block
Status: 200 OK
Cache-Control: no-cache, no-store
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Date: Mon, 07 May 2018 15:09:18 GMT
Expires: Fri, 01 Jan 1990 00:00:00 GMT
Pragma: no-cache
Server: nginx/1.4.6 (Ubuntu)
Strict-Transport-Security: max-age=15552000
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Request-Id: c89df3f0-5c0e-4be4-96d0-f8b0730ddf6d
X-Runtime: 0.009782
X-Xss-Protection: 1; mode=block
failed

**Comment by shyamkumarchauhan** [comment]
Cleared install node exported in 2nd attempt but this is the error message when I used to deploy and which has forced me to use the latest version 22.0.1...

what is the recommendation to get this fixed  ???


preparing build
checking pipeline is not paused

checking job is not paused

discovering any new versions of pcf-bosh-creds

discovering any new versions of pcf-prometheus-pipeline

discovering any new versions of prometheus-release-blob

discovering any new versions of prometheus-release-git

waiting for a suitable set of input versions
prometheus-release-blob - pinned version {"tag":"v21.1.1"} is not available
checking max-in-flight is not reached

**Comment by mkuratczyk** [comment]
The error I see is `error running command: GET https://api.github.com/repos/bosh-prometheus/node-exporter-boshrelease/releases/tags/v3.0.1: 403 API rate limit exceeded for 165.225.0.87. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.); `. You haven't provided a valid Github token and therefore Concourse's github repo check exceeded your limit quickly. Please provide the token (https://github.com/pivotal-cf/pcf-prometheus-pipeline/blob/master/pipeline/params.yml#L33).

On top of that, because currently the pipeline is pinned to prometheus-boshrelease v21 you may need to force Concourse to check for that version. Please try something like `fly -t concourse check-resource -r deploy-prometheus/prometheus-release-blob --from tag:v21.1.1` - it should force it to discover version v21.1.1 even though it's not the latest.

As I said - I hope to resolve that in the next few days by adding support for version 22 of the prometheus-boshrelease but I haven't started working on that yet.
